### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by bihline** [tetreum/erep#1]
Hello, 
When I do all the install requirements, and start the erepublik script
it shows me this error
( ! ) Fatal error: Class 'Slim\App' not found in C:\wamp\www\erep-master\bootstrap.php on line 21

Screenshoot link: 
http://image.prntscr.com/image/e8c5a79be2fc4a69b7940bab7c34695d.png

Can you please help me to solve this error 
Thanks a lot

**Comment by tetreum** [comment]
Did you follow the instructions? That error is because you didn't make composer install : S

**Comment by bihline** [comment]
Thanks, I fixed it , but 
I successfuly registred new account, but when I try to login, and click on login button 
It shows me just: 
{"error":0}

**Comment by tetreum** [comment]
That looks like if htaccess/friendly urls weren't working :s (https://github.com/tetreum/erep/blob/master/htdocs/.htaccess)

If you're not using Apache, you should convertat that, nignx ex:
```
server {
    listen   80;
    server_name erepublik.dev;

    root /var/www/erepublik/htdocs;
    index index.html index.htm index.php;

    charset utf-8;
    sendfile off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    ## The "application" requests should be processed by Slim
    location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

                # With php5-fpm:
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
    }
}
```

Notice that subdomain/domain must point to /htdocs/ folder.

Also, check browser's console. Maybe there is a JS error (post it here if its that)
