### ISSUE TITLE
How install composer in my host ?

### ISSUE THREAD

**Issue by javi2003** [tetreum/erep#2]
How install composer in my host ? pls man :D

**Comment by javi2003** [comment]
And see this error in the db :/

1 errors were found during analysis.

Missing expression. (near "ON" at position 25)

**Comment by tetreum** [comment]
Sorry but i'm not giving user support on this. If you don't know how to install composer (i mean, it's just a google search) you will hardly know how to improve the script.

db.sql may be a PostgreSQL export rather than a MySQL one. I don't remember it. Try using a converter.
