### ISSUE TITLE
nginx error: "nginx: [emerg] "server" directive is not allowed here in..."

### ISSUE THREAD

**Issue by kahric** [tetreum/erep#3]
I followed the instructions, run the composer and grunt, but the last step is taunting me. I'm totally new to nginx so I could use some help here. I made a config file called "server.conf" and put it in my erep directory, and when I try to run nginx using the command "nginx -c /Users/kahric/Documents/erep/server.conf", I get the error from the title. What am I doing wrong, how to set up this correctly? Does it interfere in any way with my Apache server that I have running? Using Mac OS X 12.4 Sierra.

Thank you for this great script, and thank you in advance for your answer.
Greetings.

**Comment by OpenHogwarts** [comment]
¿Could you publish the full error message?
It shouldn't be a problem (having nginx & apache at the same time) as long as you run them in different ports.
FYI: This script can also run in apache :o

**Comment by tetreum** [comment]
¿Could you publish the full error message?
It shouldn't be a problem (having nginx & apache at the same time) as long as you run them in different ports.
FYI: This script can also run in apache :o

Edit: I think it's this:
The example that i published in readme.md it's a vhost, not a full nginx config. When using `nginx -c` nginx expects a full nginx config not just a single virtual host.
Check nginx's default config file at `/etc/nginx/nginx.conf` and look for `Virtual Host Configs` you will see in which directory you must save the readme.md's example. (probably it's `/etc/nginx/conf.d/` or `/etc/nginx/sites-enabled/`) then just restart nginx :)

**Comment by kahric** [comment]
Thank you! After I've done that, It's working. :)

**Comment by tetreum** [comment]
Nice to hear that! Closing issue.
