### ISSUE TITLE
Do you can finish this project ?

### ISSUE THREAD

**Issue by zNexPvP** [tetreum/erep#4]
Do you can finish this project someday ?

**Comment by tetreum** [comment]
Yes, i could finish it, but i got no motivation for doing it.

**Comment by zNexPvP** [comment]
How much money do you charge to finish?

**Comment by tetreum** [comment]
What features do you miss?

**Comment by zNexPvP** [comment]
Moderation options and wars

**Comment by tetreum** [comment]
Could you take screenshots of all required war pages? i do not longer have erepublik account

**Comment by zNexPvP** [comment]
Do you have discord ?

**Comment by tetreum** [comment]
OpenHogwarts (id: 2920)
