### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by AyamareHD** [tetreum/erep#7]
Warning: require(D:\xampp\htdocs\phpMyAdmin/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\bootstrap.php on line 19

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\phpMyAdmin/vendor/autoload.php' (include_path='.;\xampp\php\PEAR') in D:\xampp\htdocs\bootstrap.php on line 19

hi tetreum!
i am getting the above error. what is the problem? i can do anything to talk to you for half an hour! :)
please add me if you are using discord: Ayamare#7373
:(

**Comment by AyamareHD** [comment]
@tetreum

**Comment by AyamareHD** [comment]
https://pasteboard.co/k9IX3pM7JJ6x.png pictures

**Comment by tetreum** [comment]
You did not follow the instructions given at https://github.com/tetreum/erep#install
The error that you're getting is because you didn't install the dependencies (`composer install`)

**Comment by AyamareHD** [comment]
hello again,

as you said, ""composer" is installed on the computer, sir.
https://prnt.sc/1wlu7pa

thanks for replying to me, i love you.

tetreum ***@***.***>, 18 Eki 2021 Pzt, 08:54 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
But you must install the dependencies, composer is the package manager.
Every step at https://github.com/tetreum/erep#install it's a literal command line that you must execute.  (except the last one)

**Comment by AyamareHD** [comment]
> But you must install the dependencies, composer is the package manager. Every step at https://github.com/tetreum/erep#install it's a literal command line that you must execute. (except the last one)

oh yeah, i managed to install "composer install". the previous error seems to have been resolved. but a new error appeared.

localhost/htdocs pictures: https://prnt.sc/1wm602w
localhost pictures: https://prnt.sc/1wm6211
www folder pictures: https://prnt.sc/1wm63rl / https://prnt.sc/1wm64m2
htdocs folder pictures: https://prnt.sc/1wm66bt

**Comment by AyamareHD** [comment]
@tetreum i fixed this problem by deleting the " 25 ". line in the conf.php file in the first picture, but i am getting a new error.

https://prnt.sc/1wm7hj4 system won't let me register (signup).

**Comment by AyamareHD** [comment]
i was able to log into the system by registering.
the page looks like this. where is the mistake? : https://prnt.sc/1wm7tbl

**Comment by AyamareHD** [comment]
i couldnt fix the error.

tetreum ***@***.***>, 18 Eki 2021 Pzt, 14:55 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
Both, the signup error and the lack of style are because you didn't run the grunt step, which is the one that compiles styles & js

**Comment by AyamareHD** [comment]
> Both, the signup error and the lack of style are because you didn't run the grunt step, which is the one that compiles styles & js

grunt is not working. : https://prnt.sc/1wmfq6l

**Comment by tetreum** [comment]
Yep, you will have to visit the link that they give you there to install the dependencies (in web eeeeeeeeeeeeeverything has 45675673534 dependencies xD)

**Comment by AyamareHD** [comment]
oh no, 
grunt is running but the problem persists.
https://prnt.sc/1wmohbn

**Comment by tetreum** [comment]
You did the hardest part now, so if it keeps failing, it will just be some stupid detail.
Try viewing the source code of the page and clicking one of the .css or .js files, let's see what does it return/show.

**Comment by AyamareHD** [comment]
looks like we're nearing the end now.most issues seem to have been resolved.
https://prnt.sc/1wmwplp

now an error appears in the console. and also there is a blue bar at the top left as seen in the picture (it goes back and forth as loading)
https://prnt.sc/1wmwvks

**Comment by AyamareHD** [comment]
error 2
https://prnt.sc/1wmxj1w
@tetreum

**Comment by AyamareHD** [comment]
it looks like there is a problem with the registry.
https://prnt.sc/1wmyc66
console: https://prnt.sc/1wmye2f

tetreum ***@***.***>, 18 Eki 2021 Pzt, 20:04 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
the blue bar is a loading bar, it appears automatically when a request is made ;)
About the failed chat request, maybe the code itself is wrong, try editing this:

On `routes.php`, where:
```php
  $app->post('/list', function($request, $response, $args) use ($app) {
            $ct = new Chat($app, $response);
            $ct->json('showMessages');
        });
```
Replace with
```php
  $app->get('/list', function($request, $response, $args) use ($app) {
            $ct = new Chat($app, $response);
            $ct->json('showMessages');
        });
```

The signup seems ok, that message is not an error, just a browser notation.

**Comment by AyamareHD** [comment]
https://prnt.sc/1wmzh3v
the theme is broken again. :O

tetreum ***@***.***>, 18 Eki 2021 Pzt, 21:28 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
notice how all errors are 404, like if compiled files weren't being generated.
Those files are generated by `grunt` command, try running the command again.
If it goes well but you still get 404, you will have to find where `built.js` is and edit the template to point it to it. This should work by default, so it's pretty strange.

**Comment by AyamareHD** [comment]
i believe most bugs will be fixed soon. i fixed the theme issue.it keeps
giving an error. Could it be a problem with the files? (also the chat is
still corrupted)

love tetreum
https://prnt.sc/1wn2gpq

tetreum ***@***.***>, 18 Eki 2021 Pzt, 21:44 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
i believe that the main issue is how are you making requests. The whole application probably expects a domain.
Try adding this line on your hosts file:
`127.0.0.1 erepublik.dev`
(or the domain that you set here https://github.com/tetreum/erep/blob/master/conf.sample.php#L28)
https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/
 
And then open that domain in the browser, http://erepublik.dev (make sure it hasn't https)

**Comment by AyamareHD** [comment]
hello again tetreum,
the new version of composer does not support php 7.0.
in the conf.php file
(
    'cookies.cipher' => MCRYPT_RIJNDAEL_256,
    'cookies.cipher_mode' => MCRYPT_MODE_CBC,
)
these two lines are preventing the files from working.
pictures: https://prnt.sc/1ws0mof

when we remove these two lines from the "conf.php" file, the files are
working.
pictures: https://prnt.sc/1ws0oma

but this time login, registration and many systems are not working.
im investigating to fix these issues. but since you are the author of the
files, it may be better to publish a new update.
if you have a solution suggestion I will be here.

regards.

tetreum ***@***.***>, 18 Eki 2021 Pzt, 22:09 tarihinde şunu
yazdı:

**Comment by tetreum** [comment]
rather than deleting them, try replacing both lines with:
```
'cookies.cipher' => "AES-128-CBC",
```

The main problem is that this project is quite old and i'm not willing to update it, as i'm not longer interested in eRepublik :(

**Comment by AyamareHD** [comment]
yeah, it has been about 5 years since the project was published.you cant
even imagine how much money these games make annually.(at least 50k euros)
you developed this project alone. you dont know what youre missing.you
should at least finish this project, even if its for money. talk to
me(discord: Ayamare#7373)

login and registration still not working. : https://prnt.sc/1wukk65

tetreum ***@***.***>, 20 Eki 2021 Çar, 10:02 tarihinde şunu
yazdı:
